### ISSUE TITLE
about transf in deproject.py

### ISSUE THREAD

**Issue by helen-poon** [domeckert/pyproffit#19]
Sorry, it is actually a little bit off topic...
In deproject.py, function Density, I think "transf" is used to convert the apec norm to hydrogen density, but it does not fully look like that as it does not have the angular diameter distance. 

`transf = 4. * (1. + z) ** 2 * (180. * 60.) ** 2 / np.pi / 1e-14 / self.nhc / Mpc * 1e3`

In particular, I don't know where 180 and 60 come from...
What I need to do is to fit the surface brightness using beta model first, and then convert it to hydrogen density. So I need to understand this term to make sure I convert it correctly.

**Comment by domeckert** [comment]
Hi @helen-poon 

Indeed it is correct that this variable allows to convert from APEC norm to emission integral and then gas density. The angular diameter cancels out because the term in the APEC norm is the volume integral 

Norm = 1e-14/(4 * pi * (1+z)^2 d_a^2) int n_e n_H dV

whereas what we care about is the emission integral EI = int n_e n_H dl. The two quantities are related to one another as

Norm = 1e-14 / (4 * pi * (1+z)^2 d_a^2) * EI * A

with A the physical area of 1 arcmin^2. The terms with 180 and 60 are thus just the conversion from arcmin^2 to steradian, and the angular diameter distance at the numerator and the denominator cancels out.

Out of curiosity, why do you want to do this with a single beta model? The Multiscale approach implemented in pyproffit already does all of these calculations for you and is much more accurate than a beta model.

**Comment by helen-poon** [comment]
Thanks, Dominique, very clear explanation. 
Yes, I know the Multiscale approach is more accurate and I did that already. My purpose is actually not to derive the electron density, but see how much the beta model underestimates the hydrostatic mass.

**Comment by domeckert** [comment]
All right, thanks. My understanding is that the beta model will indeed underestimate hydrostatic masses, and the fixed gas density slope at large radii will be a contributor, but the dominant factor is probably the assumption of a constant temperature, as it neglects the temperature gradient.

Note that pyproffit's little brother hydromass is now up and running, with documentation and everything. The papers presenting the package will be out soon. You can check out hydromass here:

https://github.com/domeckert/hydromass
