### ISSUE TITLE
Elliptical beta models?

### ISSUE THREAD

**Issue by ktrehaeven** [domeckert/pyproffit#22]
Good day. I'm a PhD student from Rhodes University, South Africa. I'm interested in using pyproffit to calc the power spectrum of x-ray surface brightness fluctuations. My primary field of study is diffuse radio emission in galaxy clusters, so please bear with my ignorance. It seems to me that pyproffit can only deal with **circular** beta or double beta models, not **elliptical** distributions. Is that correct? And if so, since the power spectrum depends heavily on the input model, could elliptical versions be written in?

**Comment by domeckert** [comment]
Hello, and thanks for using pyproffit. 

No, pyproffit can already work with elliptical models. Once you extract a surface brightness profile in elliptical annuli. To do this you need to provide the "ellipse_ratio" and "rotation_angle" parameters to the SBprofile method:

https://github.com/domeckert/pyproffit/blob/master/pyproffit/profextract.py#L328

Once the best-fit model is loaded and fitted, you can then output the model image using SaveModelImage:

https://github.com/domeckert/pyproffit/blob/master/pyproffit/profextract.py#L863

You will see that the output model will be elliptical rather than spherical.

**Comment by ktrehaeven** [comment]
Thank you very much!
