### ISSUE TITLE
Different power spectrum results given same sb model

### ISSUE THREAD

**Issue by ktrehaeven** [domeckert/pyproffit#23]
Hi

I'm trying to get the power spectrum (ps) of surface brightness (sb) residuals for a cool-core galaxy cluster. However, identical runs of the ps analysis gives different results. I've been using a double beta model. I've attached a screenshot of the parameters that the sb fitting converges to, as well as the ps and amplitude plots from identical runs using these same model parameters. Sometimes the variation is within the calculated uncertainties, sometimes not. I'm not sure if this is a matter of SNR or if something deeper is responsible. The obs is > 100 ks but I'm using a binsize of 1.476 arcsec (3 chandra pixels) to determine the profile.
![sb_model_parameters](https://github.com/domeckert/pyproffit/assets/77777044/9cbf1521-4a54-4e2b-a62e-9cd4002fe5f2)
![sb_model_profile](https://github.com/domeckert/pyproffit/assets/77777044/91aef5bd-5228-4837-8824-187152eafdee)
[power_spectrum.inner_200kpc_radius1.pdf](https://github.com/domeckert/pyproffit/files/12082978/power_spectrum.inner_200kpc_radius1.pdf)
[power_spectrum.inner_200kpc_radius2.pdf](https://github.com/domeckert/pyproffit/files/12082979/power_spectrum.inner_200kpc_radius2.pdf)

[a2d.inner_200kpc_radius1.pdf](https://github.com/domeckert/pyproffit/files/12082980/a2d.inner_200kpc_radius1.pdf)
[a2d.inner_200kpc_radius2.pdf](https://github.com/domeckert/pyproffit/files/12082984/a2d.inner_200kpc_radius2.pdf)

**Comment by domeckert** [comment]
Hi @ktrehaeven . I need to look into the power spectrum part but in any case it seems obvious from your plots that you have an issue with the background subtraction, which may be responsible for the differences that you find. I suspect that you may have subtracted the sky backkground multiple times from the same surface brightness profile, which resulted in over-subtraction.

The point is, please check your background subtraction first and find an appropriate fit to the surface brightness, otherwise the 2D model will be wrong and you will end up with different power spectra.
